### ISSUE TITLE
CSON.stringify() uses ", not '

### ISSUE THREAD

**Issue by SJAnderson** [bevry/cson#47]
stringifySync() uses double quotes in the output, would be better for readability if it had single quotes. Thoughts on this?

Currently:
```coffee
{
  name: "steve"
  gender: "male"
}
```

Desired:
```coffee
{
  name: 'steve'
  gender: 'male'
}
```

**Comment by balupton** [comment]
Fixed in v2

**Comment by samestep** [comment]
@balupton [As far as I can tell][stack overflow], this issue still persists

[stack overflow]: https://stackoverflow.com/questions/42776373/how-can-i-prevent-atom-from-making-superficial-changes-to-config-cson#comment75355966_42782840

**Comment by balupton** [comment]
guessing the fixed was an incorrect thing - this would be a cson-parser thing - we could add an option to do a conversion here, but it is likely best another package

**Comment by samestep** [comment]
Agreed; I raised an issue in `cson-parser` to resolve this.
